# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: source/conf.py
   # The config file overrides the UI settings:
   # https://github.com/pyca/cryptography/issues/5863#issuecomment-792343136
   builder: dirhtml

python:
   version: 3.8
   install:
   - requirements: requirements.txt
