name: Test translations

on:
  workflow_dispatch:
  pull_request:
    paths:
    - '**.po'
    branches:
    - translation/source
  push:
    paths:
    - '**.po'
    branches:
    - translation/source

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  I18N_BRANCH: translation/source

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.languages.outputs.languages }}

    steps:
    - name: Grab the repo src
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ env.I18N_BRANCH }}
        persist-credentials: false

    - name: List languages
      id: languages
      working-directory: locales
      run: |
        list=$(find * -maxdepth 0 -type d | jq -nRc '[inputs]')
        echo "languages=$list" >> $GITHUB_OUTPUT


  test-translation:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJson(needs.matrix.outputs.languages)}}

    steps:
    - name: Grab the repo src
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ env.I18N_BRANCH }}
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: >-
          3.10

    - name: Install Python tooling
      run: python -m pip install --upgrade nox virtualenv sphinx-lint

    - name: Set Sphinx problem matcher
      uses: sphinx-doc/github-problem-matcher@1f74d6599f4a5e89a20d3c99aab4e6a70f7bda0f # v1.1

    - name: Build translated docs in ${{ matrix.language }}
      run: nox -s build -- -q -D language=${LANGUAGE}
      env:
        LANGUAGE: ${{ matrix.language }}

    - name: Set Sphinx Lint problem matcher
      if: always()
      run: echo '::add-matcher::.github/sphinx_lint_matcher.json'

    - name: Lint translation file
      if: always()
      run: sphinx-lint locales/${LANGUAGE}/LC_MESSAGES/messages.po
      env:
        LANGUAGE: ${{ matrix.language }}
